### ISSUE TITLE
Erro de LUA

### ISSUE THREAD

**Issue by Nomeone2** [Jaliborc/Blitz#10]
Message: Interface\AddOns\Blitz\addons\progress\progress.lua:119: bad argument #1 to 'gmatch' (string expected, got nil)
Time: Mon Nov 23 16:01:10 2020
Count: 2
Stack: Interface\AddOns\Blitz\addons\progress\progress.lua:119: bad argument #1 to 'gmatch' (string expected, got nil)
[string "=(tail call)"]: ?
[string "=[C]"]: in function `gmatch'
[string "@Interface\AddOns\Blitz\addons\progress\progress.lua"]:119: in function `GetWorseItem'
[string "@Interface\AddOns\Blitz\addons\progress\progress.lua"]:91: in function `Display'
[string "@Interface\AddOns\Blitz\addons\progress\progress.lua"]:23: in function `setUpFunction'
[string "@Interface\FrameXML\AlertFrames.lua"]:177: in function `ShowAlert'
[string "@Interface\FrameXML\AlertFrames.lua"]:113: in function `AddAlert'
[string "@Interface\AddOns\Blitz\addons\progress\progress.lua"]:30: in function `ShowQuest'
[string "@Interface\AddOns\Blitz\addons\main\events.lua"]:93: in function `?'
[string "@Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

--Page2

Message: Frame <unnamed>: Unknown function AchievementShield_OnLoad in element OnLoad
Time: Mon Nov 23 16:01:10 2020
Count: 2

**Comment by Jaliborc** [comment]
Fixed!
