### ISSUE TITLE
BC Classic - Lua Error - Blitz\addons\main\events.lua:115: Usage: local isOnQuest = C_QuestLog.IsOnQuest(questID)

### ISSUE THREAD

**Issue by boktai1000** [Jaliborc/Blitz#12]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 9.1.0
 - Server patch: 2.5.2.40203

**Describe the bug**
Lua error, happened shortly after doing Fires over Skettis daily in BC Classic

**Screenshots**
![image](https://user-images.githubusercontent.com/9054563/133937352-1fa6c85f-ebc9-4f17-aa2a-e96e0e2f75d1.png)

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the first message (labelled 1/Many) that appeared.

[210919-blitz_lua.txt](https://github.com/Jaliborc/Blitz/files/7192605/210919-blitz_lua.txt)

**Comment by Jaliborc** [comment]
Fixed!
