### ISSUE TITLE
Dragonflight LUA Error

### ISSUE THREAD

**Issue by Uggers** [Jaliborc/Blitz#14]
**Running Software (issues missing this information will be deleted):**
 - Addon version: Blitz9.1.2-9.1.5
 - Server patch: 10.0.0

 **Have you read the changelog? (please don't waste our time)**
Yup read

**Describe the bug**
In general it doesn't seem to work 100%, likely due to 10.0.0 changes

**To Reproduce**
See bugsack error below

**Error Logs**
`27x Interface/AddOns/Blitz/addons/main/button.lua:21: CreateFrame(): Couldn't find inherited node "OptionsSmallCheckButtonTemplate"
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blitz/addons/main/button.lua"]:21: in main chunk

Locals:
(*temporary) = "CheckButton"
(*temporary) = "Blitz"
(*temporary) = QuestFrame {
 0 = <userdata>
 SetBorder = <function> defined @Interface/SharedXML/PortraitFrame.lua:62
 layoutType = "PortraitFrameTemplate"
 SetPortraitShown = <function> defined @Interface/SharedXML/PortraitFrame.lua:91
 SetPortraitToBag = <function> defined @Interface/SharedXML/PortraitFrame.lua:75
 SetPortraitAtlasRaw = <function> defined @Interface/SharedXML/PortraitFrame.lua:83
 GetTitleText = <function> defined @Interface/SharedXML/PortraitFrame.lua:28
 FriendshipStatusBar = StatusBar {
 }
 SetPortraitTexCoord = <function> defined @Interface/SharedXML/PortraitFrame.lua:87
 Inset = QuestFrameInset {
 }
 GetPortrait = <function> defined @Interface/SharedXML/PortraitFrame.lua:58
 SetTitleFormatted = <function> defined @Interface/SharedXML/PortraitFrame.lua:40
 NineSlice = Frame {
 }
 TopTileStreaks = Texture {
 }
 TitleContainer = Frame {
 }
 Bg = QuestFrameBg {
 }
 SetPortraitToAsset = <function> defined @Interface/SharedXML/PortraitFrame.lua:67
 SetPortraitTextureSizeAndOffset = <function> defined @Interface/SharedXML/PortraitFrame.lua:95
 SetTitleColor = <function> defined @Interface/SharedXML/PortraitFrame.lua:32
 CloseButton = QuestFrameCloseButton {
 }
 PortraitContainer = Frame {
 }
 SetPortraitToUnit = <function> defined @Interface/SharedXML/PortraitFrame.lua:71
 SetPortraitTextureRaw = <function> defined @Interface/SharedXML/PortraitFrame.lua:79
 DefaultPortraitTextureSizeAndOffset = <function> defined @Interface/SharedXML/PortraitFrame.lua:101
 SetTitle = <function> defined @Interface/SharedXML/PortraitFrame.lua:36
 SetTitleMaxLinesAndHeight = <function> defined @Interface/SharedXML/PortraitFrame.lua:49
}
(*temporary) = "OptionsSmallCheckButtonTemplate"
`

**Additional context**

**Comment by Veyska** [comment]
Tried replacing that button template with another one I'd seen suggested as a fix for a completely different addon just to see if that got things operational, even if it looked odd/incorrectly sized, and while that stopped it from complaining about *that* error I instead got this one:

`1x Blitz/addons/main/button.lua:28: Usage: self:SetFontString(fontString)
[string "=[C]"]: in function `SetFontString'
[string "@Blitz/addons/main/button.lua"]:28: in function `?'
[string "@Blitz/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:20: in function <...ceBlitz/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Blitz/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:56: in function <...ceBlitz/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:536: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:587: in function `CombatLog_LoadUI'
[string "@FrameXML/UIParent.lua"]:1484: in function <FrameXML/UIParent.lua:1362>`

**Comment by Veyska** [comment]
Not sure what prompted me to poke at this again, but while I can't remember what I tried replacing the button template bit with back then replacing 'OptionsSmallCheckButtonTemplate' (on line 21 in Blitz\addons\main\button.lua) with 'ChatConfigSmallCheckButtonTemplate' seems to get it back operational again, at least the quest automation bit (haven't tested the progress bar repeated turn-in bits though).  Can't get options panel to show but that's a whole different kettle of fish and for now this is good enough for me.  🤷‍♀️
