### ISSUE TITLE
Sushi-3.0 library packaged with Blitz incomplete?

### ISSUE THREAD

**Issue by Fonjask** [Jaliborc/Blitz#3]
Hi. Got errors that Blitz had error loading a bunch of Classes from its Sushi-3.0 lib.
Such as: TextButton, GrayButton, HelpButton, TabButtons, TextureButton, ColorPicker, IconCheck, TabGroup, TextureDropdown, and Editbox.
Opening the Sushi-3.0 lib packaged with Blitz, and comparing it with the Sushi-3.0 lib downloaded from its github (http://jaliborc.github.io/Sushi-3.0/) revealed that a bunch of classes Blitz was trying to call are not included in the library Blitz comes with.

**Comment by Veyska** [comment]
Still seemed to work fine for me, only threw errors when I opened the Interface options panel.  Finally got around to adding all the "missing" classes and now there are no errors thrown though whether it's actually doing anything with them...
