### ISSUE TITLE
Quest: Turn the Scale is missing from your database.  Location: Nazjatar (AshenStrand) 34.41, 37.90

### ISSUE THREAD

**Issue by Wizeoff** [Jaliborc/Blitz#5]
**Running Software (issues missing this information will be deleted):**
 - Addon version:
 - Server patch: [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the first message (labelled 1/Many) that appeared.

**Additional context**

**Comment by Wizeoff** [comment]
Krato Flipperfoot (55980)

**Comment by Jaliborc** [comment]
Blitz doesnt have a database. It asks the server for the quest type. That means the quest in question is miss classified.
