### ISSUE TITLE
Blitz Error

### ISSUE THREAD

**Issue by rdempsey27** [Jaliborc/Blitz#6]
Date: 2020-01-28 17:52:28
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Blitz\libs\Sushi-3.1\Sushi-3.1.lua line 27:
   attempt to index local 'Install' (a nil value)
Debug:
   [string "@Blitz\libs\Sushi-3.1\Sushi-3.1.lua"]:27: in main chunk
   [string "=[C]"]: LoadAddOn()
   [string "@Blitz\addons\main\main.lua"]:60: OnTutorials()
   [string "@Blitz\addons\main\main.lua"]:155: UpdateButton()
   [string "@Blitz\addons\main\main.lua"]:106: ?()
   [string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119:
      ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [string "=[C]"]: ?
   [string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29:
      ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   [string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: Fire()
   [string "@DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120:
      ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
Lib = <table> {
}
Base = <table> {
 __index = <table> {
 }
 __super = <table> {
 }
}
Install = nil
Root = "Interface\AddOns\"
(*temporary) = "^(.+)\Sushi[%d.-]+.lua"
(*temporary) = nil
(*temporary) = <table> {
 __index = <table> {
 }
 __super = <table> {
 }
}
(*temporary) = "Abstract"
(*temporary) = <table> {
 __index = <function> defined @Interface\AddOns\Blitz\libs\Poncho-2.0\Poncho-2.0.lua:8
 __call = <function> defined @Interface\AddOns\Blitz\libs\Poncho-2.0\Poncho-2.0.lua:12
}
(*temporary) = nil
(*temporary) = "Abstract"
(*temporary) = <table> {
 __index = <table> {
 }
 __super = <table> {
 }
}
(*temporary) = "__type"
(*temporary) = "Abstract"
(*temporary) = "attempt to index local 'Install' (a nil value)"

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  Altoholic, vr191
  AutoSellMyJunk, v1.2 
  AzeritePowerWeights, v8.3.1
  Blitz, v8.3.0
  BlitzConfig, v
  DataStore, vr66
  DataStoreAchievements, vr48
  DataStoreAgenda, vr30
  DataStoreAuctions, vr51
  DataStoreCharacters, vr44
  DataStoreContainers, vr60
  DataStoreCrafts, vr83
  DataStoreCurrencies, vr39
  DataStoreGarrisons, vr25
  DataStoreInventory, vr54
  DataStoreMails, vr53
  DataStorePets, vr45
  DataStoreQuests, vr47
  DataStoreReputations, vr44
  DataStoreSpells, vr33
  DataStoreStats, vr32
  DataStoreTalents, vr62
  DBMAzerothBfA, v
  DBMCore, v8.3.6
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DBMVPARNOLD, v8.1.5
  Details, v
  DetailsCombined, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  GTFO, v4.52.2
  Informant, v8.2.6508 (SwimmingSeadragon)
  MaxDps, v8.2.8
  MaxDpsShaman, v8.2.5
  OmniCC, v8.3.4
  Pawn, v2.3.20
  Poisoner, v8.0.1
  RaiderIO, v8.1.0 (v202001251823)
  RaiderIODBUSA, v
  RaiderIODBUSAR, v
  RaiderIODBUSH, v
  RaiderIODBUSHR, v
  RareScanner, v6.1.2
  RareShare, vv1.0.0
  RareShareMechagon, vv1.0.0
  RareShareNazjatar, vv1.0.0
  Simulationcraft, v1.12.5
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  Titan, v5.18.5.80300
  titansimulationcraft, vv1.0.5.70100-alpha5
  TitanBag, v5.18.5.80300
  TitanClock, v5.18.5.80300
  TitanGold, v5.18.5.80300
  TitanLocation, v5.18.5.80300
  TitanLootType, v5.18.5.80300
  TitanPerformance, v5.18.5.80300
  TitanRepair, v5.18.5.80300
  TitanVolume, v5.18.5.80300
  TitanXP, v5.18.5.80300
  BlizRuntimeLib_enUS v8.3.0.80300 <none>
  (ck=68a)

**Comment by LeiaJadeVader** [comment]
LUA Warning still ongoing as of 06/25/2020.

**Comment by aeger** [comment]
If you grab the newest version of Sushi-3.1 and replace Blitz\libs\Sushi-3.1\Sushi-3.1.lua with that it fix's the issue.
